wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.16.3
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1707442646.243033
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 16
      - 23
      4: 3.11.4
      5: 0.16.3
      8:
      - 1
      - 5
      13: linux-x86_64
